import { Opportunity } from "./types";

// Deadlines are generated relative to "now" so the live countdown and
// closing-soon (<72h) logic are always meaningful in a demo.
const now = Date.now();
const hours = (h: number) => new Date(now + h * 36e5).toISOString();
const daysAgo = (d: number) => new Date(now - d * 864e5).toISOString();

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "ung-unicef-turkana-2026",
    title: "Photo Essay: Climate Resilience & Water Access in Turkana",
    organization: "UNICEF Kenya Country Office",
    organizationDomain: "unicef.org",
    assignmentType: "Human Interest / Impact Storytelling",
    engagementType: "Short-term Field Mission",
    region: "East Africa",
    country: "Kenya",
    fieldSite: "Turkana County (Lodwar, Kakuma corridor)",
    securityTier: "UN Security Level 2",
    onSite: true,
    thematicFocus: "Climate & Resilience",
    source: "UNGM",
    brief:
      "Produce a high-resolution photo essay documenting community-led climate adaptation and water access programmes across Turkana. Deliverables must foreground beneficiary dignity and informed consent.",
    deliverables: [
      "60–80 edited high-res stills (RAW + graded JPEG)",
      "12 captioned hero images with metadata (IPTC)",
      "Signed informed-consent release for every identifiable subject",
      "Field caption sheet with names, locations and context",
    ],
    consentRequirements: [
      "Written informed consent (UNICEF template) for all subjects",
      "Guardian consent for any subject under 18",
      "No identifying data for children in protection contexts",
    ],
    budget: {
      stated: "USD 9,000 – 14,000 (all-inclusive)",
      currency: "USD",
      isScaleBased: false,
    },
    contact: {
      name: "Procurement, UNICEF Kenya",
      email: "supply.kenya@unicef.org",
      submissionUrl: "https://www.ungm.org/Public/Notice",
      referenceNumber: "UNICEF-KEN-2026-0417",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "UNICEF P11 Form", url: "#", kind: "P11" },
      { label: "Financial Proposal Template", url: "#", kind: "Financial" },
    ],
    postedAt: daysAgo(4),
    deadline: hours(58), // closing soon
    deadlineTimezone: "EAT (UTC+3)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "wfp-borno-emergency-2026",
    title: "Emergency Food Relief Video Documentary — Borno State",
    organization: "World Food Programme Nigeria",
    organizationDomain: "wfp.org",
    assignmentType: "Emergency & Humanitarian Response",
    engagementType: "Short-term Field Mission",
    region: "West Africa",
    country: "Nigeria",
    fieldSite: "Maiduguri & Monguno LGAs, Borno State",
    securityTier: "UN Security Level 3",
    onSite: true,
    thematicFocus: "Food Security & Agriculture",
    source: "ReliefWeb",
    brief:
      "Rapid-deployment video documentary on emergency food distribution to internally displaced populations. Must coordinate with WFP field security and adhere to do-no-harm protocols.",
    deliverables: [
      "One 4–6 min documentary (4K, 10-bit)",
      "Three 45s vertical social cutdowns",
      "Raw B-roll archive (min. 45 min graded)",
      "Multi-language subtitles (English + Hausa + Kanuri)",
    ],
    consentRequirements: [
      "Do-no-harm review sign-off before publication",
      "Informed consent for all interviewees",
      "Security clearance for all filming locations",
    ],
    budget: {
      stated: "Fee based on submitted financial proposal",
      currency: null,
      isScaleBased: true,
    },
    contact: {
      name: "WFP Nigeria Procurement Unit",
      email: "wfp.abuja.procurement@wfp.org",
      submissionUrl: "https://www.wfp.org/procurement",
      referenceNumber: "WFP-NG-RFP-2026-118",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "Technical Proposal Template", url: "#", kind: "Technical" },
      { label: "Financial Proposal Template", url: "#", kind: "Financial" },
    ],
    postedAt: daysAgo(2),
    deadline: hours(31), // closing soon
    deadlineTimezone: "WAT (UTC+1)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "unhcr-horn-lta-2026",
    title: "LTA / Vendor Roster — Visual Documentation, Horn of Africa",
    organization: "UNHCR Regional Bureau for East, Horn & Great Lakes",
    organizationDomain: "unhcr.org",
    assignmentType: "LTA / Roster Framework Agreement",
    engagementType: "Multi-Year LTA / Retainer",
    region: "East Africa",
    country: "Regional (Kenya, Ethiopia, Somalia, South Sudan)",
    fieldSite: null,
    securityTier: null,
    onSite: true,
    thematicFocus: "General Humanitarian",
    source: "UNGM",
    brief:
      "Establish a 3-year Long-Term Agreement roster of pre-qualified photography and videography vendors for refugee and displacement documentation across the Horn of Africa.",
    deliverables: [
      "Framework agreement — callable per assignment",
      "Standardised rate card (day rate + deliverable tiers)",
      "Portfolio + reference verification",
      "Compliance with UNHCR visual-storytelling guidelines",
    ],
    consentRequirements: [
      "UNHCR consent & child-safeguarding certification",
      "Data-protection compliance for refugee subjects",
    ],
    budget: {
      stated: "Framework — rates per call-off",
      currency: null,
      isScaleBased: true,
    },
    contact: {
      name: "UNHCR RBEHAGL Supply",
      email: "kensu@unhcr.org",
      submissionUrl: "https://www.ungm.org/Public/Notice",
      referenceNumber: "UNHCR-RFP-2026-EHAGL-07",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "Vendor Roster Application", url: "#", kind: "Other" },
      { label: "Portfolio Submission Link", url: "#", kind: "Portfolio" },
    ],
    postedAt: daysAgo(9),
    deadline: hours(21 * 24), // ~3 weeks
    deadlineTimezone: "EAT (UTC+3)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "stc-accra-education-2026",
    title: "Education Impact Stories — Girls' Learning, Greater Accra",
    organization: "Save the Children International — Ghana",
    organizationDomain: "savethechildren.net",
    assignmentType: "Human Interest / Impact Storytelling",
    engagementType: "Short-term Field Mission",
    region: "West Africa",
    country: "Ghana",
    fieldSite: "Greater Accra & Central Region schools",
    securityTier: null,
    onSite: true,
    thematicFocus: "Education & Youth",
    source: "INGO Direct",
    brief:
      "Capture human-interest impact stories on girls' education and safe-learning programmes. Written case studies paired with portrait photography for donor reporting.",
    deliverables: [
      "6 written impact case studies (600–800 words each)",
      "40+ edited portrait & classroom stills",
      "Two 90s social video profiles",
      "Consent-cleared caption & metadata pack",
    ],
    consentRequirements: [
      "Save the Children child-safeguarding policy adherence",
      "Guardian consent for all minors",
      "No school-location tagging in public assets",
    ],
    budget: {
      stated: "GHS 60,000 – 85,000",
      currency: "GHS",
      isScaleBased: false,
    },
    contact: {
      name: "SCI Ghana Awards & Procurement",
      email: "ghana.procurement@savethechildren.org",
      submissionUrl: "https://ghana.savethechildren.net/tenders",
      referenceNumber: "SCI-GH-2026-MED-22",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "Safeguarding Annex", url: "#", kind: "Other" },
      { label: "Financial Proposal Template", url: "#", kind: "Financial" },
    ],
    postedAt: daysAgo(6),
    deadline: hours(11 * 24),
    deadlineTimezone: "GMT (UTC+0)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "undp-senegal-sdg-2026",
    title: "SDG Progress Multimedia Kit — Coastal Resilience, Senegal",
    organization: "UNDP Senegal",
    organizationDomain: "undp.org",
    assignmentType: "Donor & Advocacy Multimedia Kit",
    engagementType: "Short-term Field Mission",
    region: "West Africa",
    country: "Senegal",
    fieldSite: "Saint-Louis & Dakar coastline",
    securityTier: null,
    onSite: true,
    thematicFocus: "Climate & Resilience",
    source: "UNGM",
    brief:
      "Develop a donor-facing multimedia kit tracking SDG 13/14 progress on coastal erosion and resilience: infographic video, hero photography and a campaign reel.",
    deliverables: [
      "One 2-min animated infographic video (FR + EN)",
      "30 edited stills for donor reports",
      "One 60s campaign reel",
      "Editable project files handed over",
    ],
    consentRequirements: [
      "Informed consent for all subjects",
      "Drone footage requires local aviation permits (contractor obtains)",
    ],
    budget: {
      stated: "Fee based on UN Consultant Salary Scale",
      currency: null,
      isScaleBased: true,
    },
    contact: {
      name: "UNDP Senegal Procurement",
      email: "procurement.sn@undp.org",
      submissionUrl: "https://www.ungm.org/Public/Notice",
      referenceNumber: "UNDP-SN-2026-093",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "UNDP P11 Form", url: "#", kind: "P11" },
    ],
    postedAt: daysAgo(3),
    deadline: hours(9 * 24),
    deadlineTimezone: "GMT (UTC+0)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "irc-southsudan-gender-2026",
    title: "Gender & Protection Field Documentary — Juba & Bentiu",
    organization: "International Rescue Committee — South Sudan",
    organizationDomain: "rescue.org",
    assignmentType: "Emergency & Humanitarian Response",
    engagementType: "Short-term Field Mission",
    region: "East Africa",
    country: "South Sudan",
    fieldSite: "Juba & Bentiu PoC sites",
    securityTier: "UN Security Level 4",
    onSite: true,
    thematicFocus: "Gender & Protection",
    source: "ReliefWeb",
    brief:
      "Sensitive field documentary on GBV prevention and women's protection programmes. Requires survivor-centred, do-no-harm production standards throughout.",
    deliverables: [
      "One 5-min protection-sensitive documentary",
      "Anonymised interview coverage where required",
      "Photo set (no identifiable survivors without explicit consent)",
      "English subtitles + transcript",
    ],
    consentRequirements: [
      "Survivor-centred consent protocol (mandatory)",
      "GBV do-no-harm review before any release",
      "Anonymisation / silhouette option offered to every subject",
    ],
    budget: {
      stated: null,
      currency: null,
      isScaleBased: true,
    },
    contact: {
      name: "IRC South Sudan Supply Chain",
      email: "ss.procurement@rescue.org",
      submissionUrl: "https://www.rescue.org/tenders",
      referenceNumber: "IRC-SS-2026-RFP-051",
    },
    attachments: [
      { label: "Terms of Reference (PDF)", url: "#", kind: "TOR" },
      { label: "GBV Media Protocol Annex", url: "#", kind: "Other" },
    ],
    postedAt: daysAgo(1),
    deadline: hours(14 * 24),
    deadlineTimezone: "CAT (UTC+2)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "who-drc-health-2026",
    title: "Health Emergencies Visual Kit — Ebola Preparedness, DRC",
    organization: "World Health Organization — DRC",
    organizationDomain: "who.int",
    assignmentType: "Donor & Advocacy Multimedia Kit",
    engagementType: "Short-term Field Mission",
    region: "Southern & Central Africa",
    country: "Democratic Republic of the Congo",
    fieldSite: "Goma & North Kivu health zones",
    securityTier: "UN Security Level 3",
    onSite: true,
    thematicFocus: "Health & Emergencies",
    source: "Search Crawlers",
    brief:
      "Visual kit documenting community health-worker preparedness and vaccination campaigns. Discovered via Google CSE (TOR PDF); credibility verified against who.int domain.",
    deliverables: [
      "Photo library (50+ stills) of health operations",
      "One 3-min preparedness explainer (FR)",
      "Infographic stills for situation reports",
    ],
    consentRequirements: [
      "Informed consent for health workers & patients",
      "Infection-prevention compliance on all sites",
    ],
    budget: {
      stated: "USD 12,000 (indicative ceiling)",
      currency: "USD",
      isScaleBased: false,
    },
    contact: {
      name: "WHO DRC Operations Support",
      email: null,
      submissionUrl: "https://www.who.int/about/procurement",
      referenceNumber: "WHO-COD-2026-EPR-14",
    },
    attachments: [{ label: "Terms of Reference (PDF)", url: "#", kind: "TOR" }],
    postedAt: daysAgo(5),
    deadline: hours(6 * 24),
    deadlineTimezone: "CAT (UTC+2)",
    credibilityScore: 0,
    verified: true,
  },
  {
    id: "oxfam-panafrica-archive-2025",
    title: "[ARCHIVED] Pan-Africa Climate Storytelling Retainer 2025",
    organization: "Oxfam International",
    organizationDomain: "oxfam.org",
    assignmentType: "LTA / Roster Framework Agreement",
    engagementType: "Multi-Year LTA / Retainer",
    region: "Pan-Africa",
    country: "Multi-country (Pan-Africa)",
    fieldSite: null,
    securityTier: null,
    onSite: false,
    thematicFocus: "Climate & Resilience",
    source: "INGO Direct",
    brief:
      "Historical retainer roster for climate storytelling across Oxfam's Pan-Africa programmes. Retained for competitive research, budget benchmarking and recurring-cycle intelligence.",
    deliverables: [
      "Retainer framework (annual call-offs)",
      "Benchmark rate card (archived)",
    ],
    consentRequirements: ["Oxfam ethical-imagery guidelines"],
    budget: {
      stated: "EUR 40,000 – 90,000 / year (historical)",
      currency: "EUR",
      isScaleBased: false,
    },
    contact: {
      name: "Oxfam Global Procurement (closed)",
      email: null,
      submissionUrl: "https://www.oxfam.org/en/procurement",
      referenceNumber: "OXF-2025-PANAF-MED-03",
    },
    attachments: [{ label: "Terms of Reference (PDF)", url: "#", kind: "TOR" }],
    postedAt: daysAgo(210),
    deadline: hours(-40 * 24), // closed — archived
    deadlineTimezone: "CET (UTC+1)",
    credibilityScore: 0,
    verified: true,
  },
];
